### ISSUE TITLE
Use more platforms and browsers on the same command line

### ISSUE THREAD

**Issue by rafaelcs** [pytest-dev/pytest-variables#19]
Hello,

Currently every `json` file I have in my project, is specified some platform and browser (exactly as shown in the documentation of this project). So now this command is working perfectly for me and generating a report in the allure:

`pytest smoke --driver BrowserStack --variables capabilities/chrome-61.json --variables capabilities/windows.json --alluredir=allure-results -v -s`

My problem is that I need to test on more platforms and browsers and generate all these results in a single allure report. So in this case I'm trying to do the below code, but is not working:

`pytest smoke --driver BrowserStack --variables capabilities/chrome-61.json --variables capabilities/windows.json --variables capabilities/chrome-61.json --variables capabilities/osx.json --alluredir=allure-results -v -s`

Is there any easy way to make this work? That is, test across multiple platforms and browsers on a single command line?

Cheers,
Rafael

**Comment by davehunt** [comment]
Hi @rafaelcs thanks for the issue report. Currently the variables gathered from the command line are combined for a single test session. It should be possible for the plugin to support a different mode, where instead of merging variables, the tests are parameterised for each file. This would mean that you'd need to use a single file for each configuration. I suspect there might be other complications, as variables are currently session scoped, but I'd certainly support a pull request that would add this feature.

**Comment by tbradley-sans** [comment]
I have exactly the same desire as @rafaelcs to be able to make a list of capabilities objects, in hopes of being able to run a pytest-selenium test on multiple browsers.

**Comment by BeyondEvil** [comment]
Apart from @tbradley-sans comment (which I think is addressed [here](https://github.com/pytest-dev/pytest-selenium/issues/203#issuecomment-468299102)), there has been no interaction with this issue for a year and a half.

I'm going to close it, but if anyone feels that is wrong, please re-open with a comment.

Cheers!
